name: Build CrownDrip DLL Injector

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Configure Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Compile Resources and CrownDrip Suite
      run: |
        rc.exe resource.rc
        cl.exe /EHsc /O2 /Fe:"CrownDrip DLL Injector.exe" main.cpp resource.res user32.lib kernel32.lib comdlg32.lib gdi32.lib /link /SUBSYSTEM:WINDOWS
        cl.exe /LD /EHsc /O2 /Fe:"CrownDripPayload.dll" payload.cpp user32.lib kernel32.lib

    - name: Upload CrownDrip Test Suite
      uses: actions/upload-artifact@v4
      with:
        name: CrownDrip-Testing-Suite
        path: |
          CrownDrip DLL Injector.exe
          CrownDripPayload.dll
        retention-days: 5
